name: Events Demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - master # master branch
      - "feature/*" # feature branches
      - "bugfix/**" # bugfix branches
    # paths: # if one of these paths is modified, the workflow will be triggered
    #   - 'src/**' # src folder
    #   - 'package.json' # package.json file
    # paths-ignore: # if one of these paths is modified, the workflow will not be triggered
    #   - 'docs/**' # ignore docs folder
    #   - 'README.md' # ignore README.md file
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
